import time
import datetime

nol  =[ 
	"  ____    ",
	" /8888\   ",
	"|0|  |0|  ",
	"|0|  |0|  ",
	"|0|  |0|  ",
	"|0|  |0|  ",
	"|0|__|0|  ",
	" \8888/   "
]

siji = [
	" ,___     ",
	"/0000|    ",
	"|0000|    ",
	"  |00|    ",
	"  |00|    ",
	"  |00|    ",
	" _|00|_   ",
	"|0,0,00|  "
]

loro  =[
	"   __     ",
	" /0000\   ",
	"|0,--,0|  ",
	"|0|  |0|  ",
	"    /0/   ",
	"   /0/    ",
	" ,/0/__   ",
	" |88888|  "
]

telu  =[
	" _____    ",
	"/80,0,8\  ",
	"|0|  |0|  ",
	"    /8/   ",
	"  |000\   ",
	"    \90|  ",
	"|8|_/90|  ",
	"|00,09/   "
]

papat =[
	" _   _   ",
	"|0| |0|  ",
	"|0| |0|  ",
	"|0|_|0|  ",
	"\8,00,8| ",
	"    |0|  ",
	"    |0|  ",
	"    |L|  "
]

lima  =[
	" ________  ",
	"|0,00,00|  ",
	"|0|        ",
	"|0|____    ",
	"|00,0090\  ",
	"      \8|  ",
	" _____/0|  ",
	"|0000,0,/  "
]

enem = [
	"  ____    ",
	" /8000|   ",
	"/8/  ''   ",
	"|8|___    ",
	"|90089\   ",
	"|0|  |0|  ",
	"|0|__|0|  ",
	" \9999/   "
]

pitu = [
	" _______   ",
	"|9999900|  ",
	"      |8/  ",
	"     /8/   ",
	"    /8/    ",
	"   /8/     ",
	"  /8/      ",
	" /8/       "
]

welu  =[
	" _____    ",
        "/80,0,8\  ",
        "|9|  |9|  ",
        "\8|__|8/  ",
        "/980,00\  ",
        "|9|  |9|  ",
        "|8|__|9|  ",
        " \8889/   "
]

sanga  =[
	" _____    ",
        "/80,0,8\  ",
        "|0|  |0|  ",
        "\9\__|8|  ",
        " \990|9|  ",
        " _   |0|  ",
        "|8|__|0|  ",
        "\86,88/   "
]

titik =[
	"      ",
	"      ",
	" __   ",
	"|;;|  ",
	"      ",
	" __   ",
	"|;;|  ",
	"      "
]

def clear():
	print "\n\n\n\n\n\n\n\n\n\n\n\n\n\n"

def out():
	jam = datetime.datetime.now().strftime("%H")
	menit = datetime.datetime.now().strftime("%M")
	clear()
	print jam+menit
	for i in [0,1,2,3,4,5,6,7]:
		a = ""
		b = ""
		if jam == "00":
			a = nol[i]+nol[i]+titik[i]
			if menit == "00": b = a+nol[i]+nol[i]
			elif menit == "01": b = a+nol[i]+siji[i]
			elif menit == "02": b = a+nol[i]+loro[i]
			elif menit == "03": b = a+nol[i]+telu[i]
                        elif menit == "04": b = a+nol[i]+papat[i]
			elif menit == "05": b = a+nol[i]+lima[i]
                        elif menit == "06": b = a+nol[i]+enem[i]
			elif menit == "07": b = a+nol[i]+pitu[i]
                        elif menit == "08": b = a+nol[i]+welu[i]
			elif menit == "09": b = a+nol[i]+sanga[i]
                        elif menit == "10": b = a+siji[i]+nol[i]
			elif menit == "11": b = a+siji[i]+siji[i]
                        elif menit == "12": b = a+siji[i]+loro[i]
                        elif menit == "13": b = a+siji[i]+telu[i]
                        elif menit == "14": b = a+siji[i]+papat[i]
                        elif menit == "15": b = a+siji[i]+lima[i]
                        elif menit == "16": b = a+siji[i]+enem[i]
                        elif menit == "17": b = a+siji[i]+pitu[i]
                        elif menit == "18": b = a+siji[i]+welu[i]
                        elif menit == "19": b = a+siji[i]+sanga[i]
			elif menit == "20": b = a+loro[i]+nol[i]
                        elif menit == "21": b = a+loro[i]+siji[i]
                        elif menit == "22": b = a+loro[i]+loro[i]
                        elif menit == "23": b = a+loro[i]+telu[i]
                        elif menit == "24": b = a+loro[i]+papat[i]
                        elif menit == "25": b = a+loro[i]+lima[i]
			elif menit == "26": b = a+loro[i]+enem[i]
                        elif menit == "27": b = a+loro[i]+pitu[i]
                        elif menit == "28": b = a+loro[i]+welu[i]
                        elif menit == "29": b = a+loro[i]+sanga[i]
                        elif menit == "30": b = a+telu[i]+nol[i]
                        elif menit == "31": b = a+telu[i]+siji[i]
                        elif menit == "32": b = a+telu[i]+loro[i]
                        elif menit == "33": b = a+telu[i]+telu[i]
                        elif menit == "34": b = a+telu[i]+papat[i]
                        elif menit == "35": b = a+telu[i]+lima[i]
                        elif menit == "36": b = a+telu[i]+enem[i]
                        elif menit == "37": b = a+telu[i]+pitu[i]
                        elif menit == "38": b = a+telu[i]+welu[i]
                        elif menit == "39": b = a+telu[i]+sanga[i]
                        elif menit == "40": b = a+papat[i]+nol[i]
                        elif menit == "41": b = a+papat[i]+siji[i]
                        elif menit == "42": b = a+papat[i]+loro[i]
                        elif menit == "43": b = a+papat[i]+telu[i]
			elif menit == "44": b = a+papat[i]+papat[i]
                        elif menit == "45": b = a+papat[i]+lima[i]
                        elif menit == "46": b = a+papat[i]+enem[i]
                        elif menit == "47": b = a+papat[i]+pitu[i]
                        elif menit == "48": b = a+papat[i]+welu[i]
                        elif menit == "49": b = a+papat[i]+sanga[i]
                        elif menit == "50": b = a+lima[i]+nol[i]
                        elif menit == "51": b = a+lima[i]+siji[i]
                        elif menit == "52": b = a+lima[i]+loro[i]
                        elif menit == "53": b = a+lima[i]+telu[i]
                        elif menit == "54": b = a+lima[i]+papat[i]
                        elif menit == "55": b = a+lima[i]+lima[i]
                        elif menit == "56": b = a+lima[i]+enem[i]
                        elif menit == "57": b = a+lima[i]+pitu[i]
                        elif menit == "58": b = a+lima[i]+welu[i]
                        elif menit == "59": b = a+lima[i]+sanga[i]
		elif jam == "01":
			a = nol[i]+siji[i]+titik[i]
			if menit == "00": b = a+nol[i]+nol[i]
			elif menit == "01": b = a+nol[i]+siji[i]
			elif menit == "02": b = a+nol[i]+loro[i]
			elif menit == "03": b = a+nol[i]+telu[i]
                        elif menit == "04": b = a+nol[i]+papat[i]
			elif menit == "05": b = a+nol[i]+lima[i]
                        elif menit == "06": b = a+nol[i]+enem[i]
			elif menit == "07": b = a+nol[i]+pitu[i]
                        elif menit == "08": b = a+nol[i]+welu[i]
			elif menit == "09": b = a+nol[i]+sanga[i]
                        elif menit == "10": b = a+siji[i]+nol[i]
			elif menit == "11": b = a+siji[i]+siji[i]
                        elif menit == "12": b = a+siji[i]+loro[i]
                        elif menit == "13": b = a+siji[i]+telu[i]
                        elif menit == "14": b = a+siji[i]+papat[i]
                        elif menit == "15": b = a+siji[i]+lima[i]
                        elif menit == "16": b = a+siji[i]+enem[i]
                        elif menit == "17": b = a+siji[i]+pitu[i]
                        elif menit == "18": b = a+siji[i]+welu[i]
                        elif menit == "19": b = a+siji[i]+sanga[i]
			elif menit == "20": b = a+loro[i]+nol[i]
                        elif menit == "21": b = a+loro[i]+siji[i]
                        elif menit == "22": b = a+loro[i]+loro[i]
                        elif menit == "23": b = a+loro[i]+telu[i]
                        elif menit == "24": b = a+loro[i]+papat[i]
                        elif menit == "25": b = a+loro[i]+lima[i]
			elif menit == "26": b = a+loro[i]+enem[i]
                        elif menit == "27": b = a+loro[i]+pitu[i]
                        elif menit == "28": b = a+loro[i]+welu[i]
                        elif menit == "29": b = a+loro[i]+sanga[i]
                        elif menit == "30": b = a+telu[i]+nol[i]
                        elif menit == "31": b = a+telu[i]+siji[i]
                        elif menit == "32": b = a+telu[i]+loro[i]
                        elif menit == "33": b = a+telu[i]+telu[i]
                        elif menit == "34": b = a+telu[i]+papat[i]
                        elif menit == "35": b = a+telu[i]+lima[i]
                        elif menit == "36": b = a+telu[i]+enem[i]
                        elif menit == "37": b = a+telu[i]+pitu[i]
                        elif menit == "38": b = a+telu[i]+welu[i]
                        elif menit == "39": b = a+telu[i]+sanga[i]
                        elif menit == "40": b = a+papat[i]+nol[i]
                        elif menit == "41": b = a+papat[i]+siji[i]
                        elif menit == "42": b = a+papat[i]+loro[i]
                        elif menit == "43": b = a+papat[i]+telu[i]
			elif menit == "44": b = a+papat[i]+papat[i]
                        elif menit == "45": b = a+papat[i]+lima[i]
                        elif menit == "46": b = a+papat[i]+enem[i]
                        elif menit == "47": b = a+papat[i]+pitu[i]
                        elif menit == "48": b = a+papat[i]+welu[i]
                        elif menit == "49": b = a+papat[i]+sanga[i]
                        elif menit == "50": b = a+lima[i]+nol[i]
                        elif menit == "51": b = a+lima[i]+siji[i]
                        elif menit == "52": b = a+lima[i]+loro[i]
                        elif menit == "53": b = a+lima[i]+telu[i]
                        elif menit == "54": b = a+lima[i]+papat[i]
                        elif menit == "55": b = a+lima[i]+lima[i]
                        elif menit == "56": b = a+lima[i]+enem[i]
                        elif menit == "57": b = a+lima[i]+pitu[i]
                        elif menit == "58": b = a+lima[i]+welu[i]
                        elif menit == "59": b = a+lima[i]+sanga[i]
		elif jam == "02":
			a = nol[i]+loro[i]+titik[i]
			if menit == "00": b = a+nol[i]+nol[i]
			elif menit == "01": b = a+nol[i]+siji[i]
			elif menit == "02": b = a+nol[i]+loro[i]
			elif menit == "03": b = a+nol[i]+telu[i]
                        elif menit == "04": b = a+nol[i]+papat[i]
			elif menit == "05": b = a+nol[i]+lima[i]
                        elif menit == "06": b = a+nol[i]+enem[i]
			elif menit == "07": b = a+nol[i]+pitu[i]
                        elif menit == "08": b = a+nol[i]+welu[i]
			elif menit == "09": b = a+nol[i]+sanga[i]
                        elif menit == "10": b = a+siji[i]+nol[i]
			elif menit == "11": b = a+siji[i]+siji[i]
                        elif menit == "12": b = a+siji[i]+loro[i]
                        elif menit == "13": b = a+siji[i]+telu[i]
                        elif menit == "14": b = a+siji[i]+papat[i]
                        elif menit == "15": b = a+siji[i]+lima[i]
                        elif menit == "16": b = a+siji[i]+enem[i]
                        elif menit == "17": b = a+siji[i]+pitu[i]
                        elif menit == "18": b = a+siji[i]+welu[i]
                        elif menit == "19": b = a+siji[i]+sanga[i]
			elif menit == "20": b = a+loro[i]+nol[i]
                        elif menit == "21": b = a+loro[i]+siji[i]
                        elif menit == "22": b = a+loro[i]+loro[i]
                        elif menit == "23": b = a+loro[i]+telu[i]
                        elif menit == "24": b = a+loro[i]+papat[i]
                        elif menit == "25": b = a+loro[i]+lima[i]
			elif menit == "26": b = a+loro[i]+enem[i]
                        elif menit == "27": b = a+loro[i]+pitu[i]
                        elif menit == "28": b = a+loro[i]+welu[i]
                        elif menit == "29": b = a+loro[i]+sanga[i]
                        elif menit == "30": b = a+telu[i]+nol[i]
                        elif menit == "31": b = a+telu[i]+siji[i]
                        elif menit == "32": b = a+telu[i]+loro[i]
                        elif menit == "33": b = a+telu[i]+telu[i]
                        elif menit == "34": b = a+telu[i]+papat[i]
                        elif menit == "35": b = a+telu[i]+lima[i]
                        elif menit == "36": b = a+telu[i]+enem[i]
                        elif menit == "37": b = a+telu[i]+pitu[i]
                        elif menit == "38": b = a+telu[i]+welu[i]
                        elif menit == "39": b = a+telu[i]+sanga[i]
                        elif menit == "40": b = a+papat[i]+nol[i]
                        elif menit == "41": b = a+papat[i]+siji[i]
                        elif menit == "42": b = a+papat[i]+loro[i]
                        elif menit == "43": b = a+papat[i]+telu[i]
			elif menit == "44": b = a+papat[i]+papat[i]
                        elif menit == "45": b = a+papat[i]+lima[i]
                        elif menit == "46": b = a+papat[i]+enem[i]
                        elif menit == "47": b = a+papat[i]+pitu[i]
                        elif menit == "48": b = a+papat[i]+welu[i]
                        elif menit == "49": b = a+papat[i]+sanga[i]
                        elif menit == "50": b = a+lima[i]+nol[i]
                        elif menit == "51": b = a+lima[i]+siji[i]
                        elif menit == "52": b = a+lima[i]+loro[i]
                        elif menit == "53": b = a+lima[i]+telu[i]
                        elif menit == "54": b = a+lima[i]+papat[i]
                        elif menit == "55": b = a+lima[i]+lima[i]
                        elif menit == "56": b = a+lima[i]+enem[i]
                        elif menit == "57": b = a+lima[i]+pitu[i]
                        elif menit == "58": b = a+lima[i]+welu[i]
                        elif menit == "59": b = a+lima[i]+sanga[i]
		elif jam == "03":
			a = nol[i]+telu[i]+titik[i]
			if menit == "00": b = a+nol[i]+nol[i]
			elif menit == "01": b = a+nol[i]+siji[i]
			elif menit == "02": b = a+nol[i]+loro[i]
			elif menit == "03": b = a+nol[i]+telu[i]
                        elif menit == "04": b = a+nol[i]+papat[i]
			elif menit == "05": b = a+nol[i]+lima[i]
                        elif menit == "06": b = a+nol[i]+enem[i]
			elif menit == "07": b = a+nol[i]+pitu[i]
                        elif menit == "08": b = a+nol[i]+welu[i]
			elif menit == "09": b = a+nol[i]+sanga[i]
                        elif menit == "10": b = a+siji[i]+nol[i]
			elif menit == "11": b = a+siji[i]+siji[i]
                        elif menit == "12": b = a+siji[i]+loro[i]
                        elif menit == "13": b = a+siji[i]+telu[i]
                        elif menit == "14": b = a+siji[i]+papat[i]
                        elif menit == "15": b = a+siji[i]+lima[i]
                        elif menit == "16": b = a+siji[i]+enem[i]
                        elif menit == "17": b = a+siji[i]+pitu[i]
                        elif menit == "18": b = a+siji[i]+welu[i]
                        elif menit == "19": b = a+siji[i]+sanga[i]
			elif menit == "20": b = a+loro[i]+nol[i]
                        elif menit == "21": b = a+loro[i]+siji[i]
                        elif menit == "22": b = a+loro[i]+loro[i]
                        elif menit == "23": b = a+loro[i]+telu[i]
                        elif menit == "24": b = a+loro[i]+papat[i]
                        elif menit == "25": b = a+loro[i]+lima[i]
			elif menit == "26": b = a+loro[i]+enem[i]
                        elif menit == "27": b = a+loro[i]+pitu[i]
                        elif menit == "28": b = a+loro[i]+welu[i]
                        elif menit == "29": b = a+loro[i]+sanga[i]
                        elif menit == "30": b = a+telu[i]+nol[i]
                        elif menit == "31": b = a+telu[i]+siji[i]
                        elif menit == "32": b = a+telu[i]+loro[i]
                        elif menit == "33": b = a+telu[i]+telu[i]
                        elif menit == "34": b = a+telu[i]+papat[i]
                        elif menit == "35": b = a+telu[i]+lima[i]
                        elif menit == "36": b = a+telu[i]+enem[i]
                        elif menit == "37": b = a+telu[i]+pitu[i]
                        elif menit == "38": b = a+telu[i]+welu[i]
                        elif menit == "39": b = a+telu[i]+sanga[i]
                        elif menit == "40": b = a+papat[i]+nol[i]
                        elif menit == "41": b = a+papat[i]+siji[i]
                        elif menit == "42": b = a+papat[i]+loro[i]
                        elif menit == "43": b = a+papat[i]+telu[i]
			elif menit == "44": b = a+papat[i]+papat[i]
                        elif menit == "45": b = a+papat[i]+lima[i]
                        elif menit == "46": b = a+papat[i]+enem[i]
                        elif menit == "47": b = a+papat[i]+pitu[i]
                        elif menit == "48": b = a+papat[i]+welu[i]
                        elif menit == "49": b = a+papat[i]+sanga[i]
                        elif menit == "50": b = a+lima[i]+nol[i]
                        elif menit == "51": b = a+lima[i]+siji[i]
                        elif menit == "52": b = a+lima[i]+loro[i]
                        elif menit == "53": b = a+lima[i]+telu[i]
                        elif menit == "54": b = a+lima[i]+papat[i]
                        elif menit == "55": b = a+lima[i]+lima[i]
                        elif menit == "56": b = a+lima[i]+enem[i]
                        elif menit == "57": b = a+lima[i]+pitu[i]
                        elif menit == "58": b = a+lima[i]+welu[i]
                        elif menit == "59": b = a+lima[i]+sanga[i]
		elif jam == "04":
			a = nol[i]+papat[i]+titik[i]
			if menit == "00": b = a+nol[i]+nol[i]
			elif menit == "01": b = a+nol[i]+siji[i]
			elif menit == "02": b = a+nol[i]+loro[i]
			elif menit == "03": b = a+nol[i]+telu[i]
                        elif menit == "04": b = a+nol[i]+papat[i]
			elif menit == "05": b = a+nol[i]+lima[i]
                        elif menit == "06": b = a+nol[i]+enem[i]
			elif menit == "07": b = a+nol[i]+pitu[i]
                        elif menit == "08": b = a+nol[i]+welu[i]
			elif menit == "09": b = a+nol[i]+sanga[i]
                        elif menit == "10": b = a+siji[i]+nol[i]
			elif menit == "11": b = a+siji[i]+siji[i]
                        elif menit == "12": b = a+siji[i]+loro[i]
                        elif menit == "13": b = a+siji[i]+telu[i]
                        elif menit == "14": b = a+siji[i]+papat[i]
                        elif menit == "15": b = a+siji[i]+lima[i]
                        elif menit == "16": b = a+siji[i]+enem[i]
                        elif menit == "17": b = a+siji[i]+pitu[i]
                        elif menit == "18": b = a+siji[i]+welu[i]
                        elif menit == "19": b = a+siji[i]+sanga[i]
			elif menit == "20": b = a+loro[i]+nol[i]
                        elif menit == "21": b = a+loro[i]+siji[i]
                        elif menit == "22": b = a+loro[i]+loro[i]
                        elif menit == "23": b = a+loro[i]+telu[i]
                        elif menit == "24": b = a+loro[i]+papat[i]
                        elif menit == "25": b = a+loro[i]+lima[i]
			elif menit == "26": b = a+loro[i]+enem[i]
                        elif menit == "27": b = a+loro[i]+pitu[i]
                        elif menit == "28": b = a+loro[i]+welu[i]
                        elif menit == "29": b = a+loro[i]+sanga[i]
                        elif menit == "30": b = a+telu[i]+nol[i]
                        elif menit == "31": b = a+telu[i]+siji[i]
                        elif menit == "32": b = a+telu[i]+loro[i]
                        elif menit == "33": b = a+telu[i]+telu[i]
                        elif menit == "34": b = a+telu[i]+papat[i]
                        elif menit == "35": b = a+telu[i]+lima[i]
                        elif menit == "36": b = a+telu[i]+enem[i]
                        elif menit == "37": b = a+telu[i]+pitu[i]
                        elif menit == "38": b = a+telu[i]+welu[i]
                        elif menit == "39": b = a+telu[i]+sanga[i]
                        elif menit == "40": b = a+papat[i]+nol[i]
                        elif menit == "41": b = a+papat[i]+siji[i]
                        elif menit == "42": b = a+papat[i]+loro[i]
                        elif menit == "43": b = a+papat[i]+telu[i]
			elif menit == "44": b = a+papat[i]+papat[i]
                        elif menit == "45": b = a+papat[i]+lima[i]
                        elif menit == "46": b = a+papat[i]+enem[i]
                        elif menit == "47": b = a+papat[i]+pitu[i]
                        elif menit == "48": b = a+papat[i]+welu[i]
                        elif menit == "49": b = a+papat[i]+sanga[i]
                        elif menit == "50": b = a+lima[i]+nol[i]
                        elif menit == "51": b = a+lima[i]+siji[i]
                        elif menit == "52": b = a+lima[i]+loro[i]
                        elif menit == "53": b = a+lima[i]+telu[i]
                        elif menit == "54": b = a+lima[i]+papat[i]
                        elif menit == "55": b = a+lima[i]+lima[i]
                        elif menit == "56": b = a+lima[i]+enem[i]
                        elif menit == "57": b = a+lima[i]+pitu[i]
                        elif menit == "58": b = a+lima[i]+welu[i]
                        elif menit == "59": b = a+lima[i]+sanga[i]
		elif jam == "05":
			a = nol[i]+lima[i]+titik[i]
			if menit == "00": b = a+nol[i]+nol[i]
			elif menit == "01": b = a+nol[i]+siji[i]
			elif menit == "02": b = a+nol[i]+loro[i]
			elif menit == "03": b = a+nol[i]+telu[i]
                        elif menit == "04": b = a+nol[i]+papat[i]
			elif menit == "05": b = a+nol[i]+lima[i]
                        elif menit == "06": b = a+nol[i]+enem[i]
			elif menit == "07": b = a+nol[i]+pitu[i]
                        elif menit == "08": b = a+nol[i]+welu[i]
			elif menit == "09": b = a+nol[i]+sanga[i]
                        elif menit == "10": b = a+siji[i]+nol[i]
			elif menit == "11": b = a+siji[i]+siji[i]
                        elif menit == "12": b = a+siji[i]+loro[i]
                        elif menit == "13": b = a+siji[i]+telu[i]
                        elif menit == "14": b = a+siji[i]+papat[i]
                        elif menit == "15": b = a+siji[i]+lima[i]
                        elif menit == "16": b = a+siji[i]+enem[i]
                        elif menit == "17": b = a+siji[i]+pitu[i]
                        elif menit == "18": b = a+siji[i]+welu[i]
                        elif menit == "19": b = a+siji[i]+sanga[i]
			elif menit == "20": b = a+loro[i]+nol[i]
                        elif menit == "21": b = a+loro[i]+siji[i]
                        elif menit == "22": b = a+loro[i]+loro[i]
                        elif menit == "23": b = a+loro[i]+telu[i]
                        elif menit == "24": b = a+loro[i]+papat[i]
                        elif menit == "25": b = a+loro[i]+lima[i]
			elif menit == "26": b = a+loro[i]+enem[i]
                        elif menit == "27": b = a+loro[i]+pitu[i]
                        elif menit == "28": b = a+loro[i]+welu[i]
                        elif menit == "29": b = a+loro[i]+sanga[i]
                        elif menit == "30": b = a+telu[i]+nol[i]
                        elif menit == "31": b = a+telu[i]+siji[i]
                        elif menit == "32": b = a+telu[i]+loro[i]
                        elif menit == "33": b = a+telu[i]+telu[i]
                        elif menit == "34": b = a+telu[i]+papat[i]
                        elif menit == "35": b = a+telu[i]+lima[i]
                        elif menit == "36": b = a+telu[i]+enem[i]
                        elif menit == "37": b = a+telu[i]+pitu[i]
                        elif menit == "38": b = a+telu[i]+welu[i]
                        elif menit == "39": b = a+telu[i]+sanga[i]
                        elif menit == "40": b = a+papat[i]+nol[i]
                        elif menit == "41": b = a+papat[i]+siji[i]
                        elif menit == "42": b = a+papat[i]+loro[i]
                        elif menit == "43": b = a+papat[i]+telu[i]
			elif menit == "44": b = a+papat[i]+papat[i]
                        elif menit == "45": b = a+papat[i]+lima[i]
                        elif menit == "46": b = a+papat[i]+enem[i]
                        elif menit == "47": b = a+papat[i]+pitu[i]
                        elif menit == "48": b = a+papat[i]+welu[i]
                        elif menit == "49": b = a+papat[i]+sanga[i]
                        elif menit == "50": b = a+lima[i]+nol[i]
                        elif menit == "51": b = a+lima[i]+siji[i]
                        elif menit == "52": b = a+lima[i]+loro[i]
                        elif menit == "53": b = a+lima[i]+telu[i]
                        elif menit == "54": b = a+lima[i]+papat[i]
                        elif menit == "55": b = a+lima[i]+lima[i]
                        elif menit == "56": b = a+lima[i]+enem[i]
                        elif menit == "57": b = a+lima[i]+pitu[i]
                        elif menit == "58": b = a+lima[i]+welu[i]
                        elif menit == "59": b = a+lima[i]+sanga[i]
		elif jam == "06":
			a = nol[i]+enem[i]+titik[i]
			if menit == "00": b = a+nol[i]+nol[i]
			elif menit == "01": b = a+nol[i]+siji[i]
			elif menit == "02": b = a+nol[i]+loro[i]
			elif menit == "03": b = a+nol[i]+telu[i]
                        elif menit == "04": b = a+nol[i]+papat[i]
			elif menit == "05": b = a+nol[i]+lima[i]
                        elif menit == "06": b = a+nol[i]+enem[i]
			elif menit == "07": b = a+nol[i]+pitu[i]
                        elif menit == "08": b = a+nol[i]+welu[i]
			elif menit == "09": b = a+nol[i]+sanga[i]
                        elif menit == "10": b = a+siji[i]+nol[i]
			elif menit == "11": b = a+siji[i]+siji[i]
                        elif menit == "12": b = a+siji[i]+loro[i]
                        elif menit == "13": b = a+siji[i]+telu[i]
                        elif menit == "14": b = a+siji[i]+papat[i]
                        elif menit == "15": b = a+siji[i]+lima[i]
                        elif menit == "16": b = a+siji[i]+enem[i]
                        elif menit == "17": b = a+siji[i]+pitu[i]
                        elif menit == "18": b = a+siji[i]+welu[i]
                        elif menit == "19": b = a+siji[i]+sanga[i]
			elif menit == "20": b = a+loro[i]+nol[i]
                        elif menit == "21": b = a+loro[i]+siji[i]
                        elif menit == "22": b = a+loro[i]+loro[i]
                        elif menit == "23": b = a+loro[i]+telu[i]
                        elif menit == "24": b = a+loro[i]+papat[i]
                        elif menit == "25": b = a+loro[i]+lima[i]
			elif menit == "26": b = a+loro[i]+enem[i]
                        elif menit == "27": b = a+loro[i]+pitu[i]
                        elif menit == "28": b = a+loro[i]+welu[i]
                        elif menit == "29": b = a+loro[i]+sanga[i]
                        elif menit == "30": b = a+telu[i]+nol[i]
                        elif menit == "31": b = a+telu[i]+siji[i]
                        elif menit == "32": b = a+telu[i]+loro[i]
                        elif menit == "33": b = a+telu[i]+telu[i]
                        elif menit == "34": b = a+telu[i]+papat[i]
                        elif menit == "35": b = a+telu[i]+lima[i]
                        elif menit == "36": b = a+telu[i]+enem[i]
                        elif menit == "37": b = a+telu[i]+pitu[i]
                        elif menit == "38": b = a+telu[i]+welu[i]
                        elif menit == "39": b = a+telu[i]+sanga[i]
                        elif menit == "40": b = a+papat[i]+nol[i]
                        elif menit == "41": b = a+papat[i]+siji[i]
                        elif menit == "42": b = a+papat[i]+loro[i]
                        elif menit == "43": b = a+papat[i]+telu[i]
			elif menit == "44": b = a+papat[i]+papat[i]
                        elif menit == "45": b = a+papat[i]+lima[i]
                        elif menit == "46": b = a+papat[i]+enem[i]
                        elif menit == "47": b = a+papat[i]+pitu[i]
                        elif menit == "48": b = a+papat[i]+welu[i]
                        elif menit == "49": b = a+papat[i]+sanga[i]
                        elif menit == "50": b = a+lima[i]+nol[i]
                        elif menit == "51": b = a+lima[i]+siji[i]
                        elif menit == "52": b = a+lima[i]+loro[i]
                        elif menit == "53": b = a+lima[i]+telu[i]
                        elif menit == "54": b = a+lima[i]+papat[i]
                        elif menit == "55": b = a+lima[i]+lima[i]
                        elif menit == "56": b = a+lima[i]+enem[i]
                        elif menit == "57": b = a+lima[i]+pitu[i]
                        elif menit == "58": b = a+lima[i]+welu[i]
                        elif menit == "59": b = a+lima[i]+sanga[i]
		elif jam == "07":
			a = nol[i]+pitu[i]+titik[i]
			if menit == "00": b = a+nol[i]+nol[i]
			elif menit == "01": b = a+nol[i]+siji[i]
			elif menit == "02": b = a+nol[i]+loro[i]
			elif menit == "03": b = a+nol[i]+telu[i]
                        elif menit == "04": b = a+nol[i]+papat[i]
			elif menit == "05": b = a+nol[i]+lima[i]
                        elif menit == "06": b = a+nol[i]+enem[i]
			elif menit == "07": b = a+nol[i]+pitu[i]
                        elif menit == "08": b = a+nol[i]+welu[i]
			elif menit == "09": b = a+nol[i]+sanga[i]
                        elif menit == "10": b = a+siji[i]+nol[i]
			elif menit == "11": b = a+siji[i]+siji[i]
                        elif menit == "12": b = a+siji[i]+loro[i]
                        elif menit == "13": b = a+siji[i]+telu[i]
                        elif menit == "14": b = a+siji[i]+papat[i]
                        elif menit == "15": b = a+siji[i]+lima[i]
                        elif menit == "16": b = a+siji[i]+enem[i]
                        elif menit == "17": b = a+siji[i]+pitu[i]
                        elif menit == "18": b = a+siji[i]+welu[i]
                        elif menit == "19": b = a+siji[i]+sanga[i]
			elif menit == "20": b = a+loro[i]+nol[i]
                        elif menit == "21": b = a+loro[i]+siji[i]
                        elif menit == "22": b = a+loro[i]+loro[i]
                        elif menit == "23": b = a+loro[i]+telu[i]
                        elif menit == "24": b = a+loro[i]+papat[i]
                        elif menit == "25": b = a+loro[i]+lima[i]
			elif menit == "26": b = a+loro[i]+enem[i]
                        elif menit == "27": b = a+loro[i]+pitu[i]
                        elif menit == "28": b = a+loro[i]+welu[i]
                        elif menit == "29": b = a+loro[i]+sanga[i]
                        elif menit == "30": b = a+telu[i]+nol[i]
                        elif menit == "31": b = a+telu[i]+siji[i]
                        elif menit == "32": b = a+telu[i]+loro[i]
                        elif menit == "33": b = a+telu[i]+telu[i]
                        elif menit == "34": b = a+telu[i]+papat[i]
                        elif menit == "35": b = a+telu[i]+lima[i]
                        elif menit == "36": b = a+telu[i]+enem[i]
                        elif menit == "37": b = a+telu[i]+pitu[i]
                        elif menit == "38": b = a+telu[i]+welu[i]
                        elif menit == "39": b = a+telu[i]+sanga[i]
                        elif menit == "40": b = a+papat[i]+nol[i]
                        elif menit == "41": b = a+papat[i]+siji[i]
                        elif menit == "42": b = a+papat[i]+loro[i]
                        elif menit == "43": b = a+papat[i]+telu[i]
			elif menit == "44": b = a+papat[i]+papat[i]
                        elif menit == "45": b = a+papat[i]+lima[i]
                        elif menit == "46": b = a+papat[i]+enem[i]
                        elif menit == "47": b = a+papat[i]+pitu[i]
                        elif menit == "48": b = a+papat[i]+welu[i]
                        elif menit == "49": b = a+papat[i]+sanga[i]
                        elif menit == "50": b = a+lima[i]+nol[i]
                        elif menit == "51": b = a+lima[i]+siji[i]
                        elif menit == "52": b = a+lima[i]+loro[i]
                        elif menit == "53": b = a+lima[i]+telu[i]
                        elif menit == "54": b = a+lima[i]+papat[i]
                        elif menit == "55": b = a+lima[i]+lima[i]
                        elif menit == "56": b = a+lima[i]+enem[i]
                        elif menit == "57": b = a+lima[i]+pitu[i]
                        elif menit == "58": b = a+lima[i]+welu[i]
                        elif menit == "59": b = a+lima[i]+sanga[i]
		elif jam == "08":
			a = nol[i]+welu[i]+titik[i]
			if menit == "00": b = a+nol[i]+nol[i]
			elif menit == "01": b = a+nol[i]+siji[i]
			elif menit == "02": b = a+nol[i]+loro[i]
			elif menit == "03": b = a+nol[i]+telu[i]
                        elif menit == "04": b = a+nol[i]+papat[i]
			elif menit == "05": b = a+nol[i]+lima[i]
                        elif menit == "06": b = a+nol[i]+enem[i]
			elif menit == "07": b = a+nol[i]+pitu[i]
                        elif menit == "08": b = a+nol[i]+welu[i]
			elif menit == "09": b = a+nol[i]+sanga[i]
                        elif menit == "10": b = a+siji[i]+nol[i]
			elif menit == "11": b = a+siji[i]+siji[i]
                        elif menit == "12": b = a+siji[i]+loro[i]
                        elif menit == "13": b = a+siji[i]+telu[i]
                        elif menit == "14": b = a+siji[i]+papat[i]
                        elif menit == "15": b = a+siji[i]+lima[i]
                        elif menit == "16": b = a+siji[i]+enem[i]
                        elif menit == "17": b = a+siji[i]+pitu[i]
                        elif menit == "18": b = a+siji[i]+welu[i]
                        elif menit == "19": b = a+siji[i]+sanga[i]
			elif menit == "20": b = a+loro[i]+nol[i]
                        elif menit == "21": b = a+loro[i]+siji[i]
                        elif menit == "22": b = a+loro[i]+loro[i]
                        elif menit == "23": b = a+loro[i]+telu[i]
                        elif menit == "24": b = a+loro[i]+papat[i]
                        elif menit == "25": b = a+loro[i]+lima[i]
			elif menit == "26": b = a+loro[i]+enem[i]
                        elif menit == "27": b = a+loro[i]+pitu[i]
                        elif menit == "28": b = a+loro[i]+welu[i]
                        elif menit == "29": b = a+loro[i]+sanga[i]
                        elif menit == "30": b = a+telu[i]+nol[i]
                        elif menit == "31": b = a+telu[i]+siji[i]
                        elif menit == "32": b = a+telu[i]+loro[i]
                        elif menit == "33": b = a+telu[i]+telu[i]
                        elif menit == "34": b = a+telu[i]+papat[i]
                        elif menit == "35": b = a+telu[i]+lima[i]
                        elif menit == "36": b = a+telu[i]+enem[i]
                        elif menit == "37": b = a+telu[i]+pitu[i]
                        elif menit == "38": b = a+telu[i]+welu[i]
                        elif menit == "39": b = a+telu[i]+sanga[i]
                        elif menit == "40": b = a+papat[i]+nol[i]
                        elif menit == "41": b = a+papat[i]+siji[i]
                        elif menit == "42": b = a+papat[i]+loro[i]
                        elif menit == "43": b = a+papat[i]+telu[i]
			elif menit == "44": b = a+papat[i]+papat[i]
                        elif menit == "45": b = a+papat[i]+lima[i]
                        elif menit == "46": b = a+papat[i]+enem[i]
                        elif menit == "47": b = a+papat[i]+pitu[i]
                        elif menit == "48": b = a+papat[i]+welu[i]
                        elif menit == "49": b = a+papat[i]+sanga[i]
                        elif menit == "50": b = a+lima[i]+nol[i]
                        elif menit == "51": b = a+lima[i]+siji[i]
                        elif menit == "52": b = a+lima[i]+loro[i]
                        elif menit == "53": b = a+lima[i]+telu[i]
                        elif menit == "54": b = a+lima[i]+papat[i]
                        elif menit == "55": b = a+lima[i]+lima[i]
                        elif menit == "56": b = a+lima[i]+enem[i]
                        elif menit == "57": b = a+lima[i]+pitu[i]
                        elif menit == "58": b = a+lima[i]+welu[i]
                        elif menit == "59": b = a+lima[i]+sanga[i]
		elif jam == "09":
			a = nol[i]+sanga[i]+titik[i]
			if menit == "00": b = a+nol[i]+nol[i]
			elif menit == "01": b = a+nol[i]+siji[i]
			elif menit == "02": b = a+nol[i]+loro[i]
			elif menit == "03": b = a+nol[i]+telu[i]
                        elif menit == "04": b = a+nol[i]+papat[i]
			elif menit == "05": b = a+nol[i]+lima[i]
                        elif menit == "06": b = a+nol[i]+enem[i]
			elif menit == "07": b = a+nol[i]+pitu[i]
                        elif menit == "08": b = a+nol[i]+welu[i]
			elif menit == "09": b = a+nol[i]+sanga[i]
                        elif menit == "10": b = a+siji[i]+nol[i]
			elif menit == "11": b = a+siji[i]+siji[i]
                        elif menit == "12": b = a+siji[i]+loro[i]
                        elif menit == "13": b = a+siji[i]+telu[i]
                        elif menit == "14": b = a+siji[i]+papat[i]
                        elif menit == "15": b = a+siji[i]+lima[i]
                        elif menit == "16": b = a+siji[i]+enem[i]
                        elif menit == "17": b = a+siji[i]+pitu[i]
                        elif menit == "18": b = a+siji[i]+welu[i]
                        elif menit == "19": b = a+siji[i]+sanga[i]
			elif menit == "20": b = a+loro[i]+nol[i]
                        elif menit == "21": b = a+loro[i]+siji[i]
                        elif menit == "22": b = a+loro[i]+loro[i]
                        elif menit == "23": b = a+loro[i]+telu[i]
                        elif menit == "24": b = a+loro[i]+papat[i]
                        elif menit == "25": b = a+loro[i]+lima[i]
			elif menit == "26": b = a+loro[i]+enem[i]
                        elif menit == "27": b = a+loro[i]+pitu[i]
                        elif menit == "28": b = a+loro[i]+welu[i]
                        elif menit == "29": b = a+loro[i]+sanga[i]
                        elif menit == "30": b = a+telu[i]+nol[i]
                        elif menit == "31": b = a+telu[i]+siji[i]
                        elif menit == "32": b = a+telu[i]+loro[i]
                        elif menit == "33": b = a+telu[i]+telu[i]
                        elif menit == "34": b = a+telu[i]+papat[i]
                        elif menit == "35": b = a+telu[i]+lima[i]
                        elif menit == "36": b = a+telu[i]+enem[i]
                        elif menit == "37": b = a+telu[i]+pitu[i]
                        elif menit == "38": b = a+telu[i]+welu[i]
                        elif menit == "39": b = a+telu[i]+sanga[i]
                        elif menit == "40": b = a+papat[i]+nol[i]
                        elif menit == "41": b = a+papat[i]+siji[i]
                        elif menit == "42": b = a+papat[i]+loro[i]
                        elif menit == "43": b = a+papat[i]+telu[i]
			elif menit == "44": b = a+papat[i]+papat[i]
                        elif menit == "45": b = a+papat[i]+lima[i]
                        elif menit == "46": b = a+papat[i]+enem[i]
                        elif menit == "47": b = a+papat[i]+pitu[i]
                        elif menit == "48": b = a+papat[i]+welu[i]
                        elif menit == "49": b = a+papat[i]+sanga[i]
                        elif menit == "50": b = a+lima[i]+nol[i]
                        elif menit == "51": b = a+lima[i]+siji[i]
                        elif menit == "52": b = a+lima[i]+loro[i]
                        elif menit == "53": b = a+lima[i]+telu[i]
                        elif menit == "54": b = a+lima[i]+papat[i]
                        elif menit == "55": b = a+lima[i]+lima[i]
                        elif menit == "56": b = a+lima[i]+enem[i]
                        elif menit == "57": b = a+lima[i]+pitu[i]
                        elif menit == "58": b = a+lima[i]+welu[i]
                        elif menit == "59": b = a+lima[i]+sanga[i]
		elif jam == "10":
			a = siji[i]+nol[i]+titik[i]
			if menit == "00": b = a+nol[i]+nol[i]
			elif menit == "01": b = a+nol[i]+siji[i]
			elif menit == "02": b = a+nol[i]+loro[i]
			elif menit == "03": b = a+nol[i]+telu[i]
                        elif menit == "04": b = a+nol[i]+papat[i]
			elif menit == "05": b = a+nol[i]+lima[i]
                        elif menit == "06": b = a+nol[i]+enem[i]
			elif menit == "07": b = a+nol[i]+pitu[i]
                        elif menit == "08": b = a+nol[i]+welu[i]
			elif menit == "09": b = a+nol[i]+sanga[i]
                        elif menit == "10": b = a+siji[i]+nol[i]
			elif menit == "11": b = a+siji[i]+siji[i]
                        elif menit == "12": b = a+siji[i]+loro[i]
                        elif menit == "13": b = a+siji[i]+telu[i]
                        elif menit == "14": b = a+siji[i]+papat[i]
                        elif menit == "15": b = a+siji[i]+lima[i]
                        elif menit == "16": b = a+siji[i]+enem[i]
                        elif menit == "17": b = a+siji[i]+pitu[i]
                        elif menit == "18": b = a+siji[i]+welu[i]
                        elif menit == "19": b = a+siji[i]+sanga[i]
			elif menit == "20": b = a+loro[i]+nol[i]
                        elif menit == "21": b = a+loro[i]+siji[i]
                        elif menit == "22": b = a+loro[i]+loro[i]
                        elif menit == "23": b = a+loro[i]+telu[i]
                        elif menit == "24": b = a+loro[i]+papat[i]
                        elif menit == "25": b = a+loro[i]+lima[i]
			elif menit == "26": b = a+loro[i]+enem[i]
                        elif menit == "27": b = a+loro[i]+pitu[i]
                        elif menit == "28": b = a+loro[i]+welu[i]
                        elif menit == "29": b = a+loro[i]+sanga[i]
                        elif menit == "30": b = a+telu[i]+nol[i]
                        elif menit == "31": b = a+telu[i]+siji[i]
                        elif menit == "32": b = a+telu[i]+loro[i]
                        elif menit == "33": b = a+telu[i]+telu[i]
                        elif menit == "34": b = a+telu[i]+papat[i]
                        elif menit == "35": b = a+telu[i]+lima[i]
                        elif menit == "36": b = a+telu[i]+enem[i]
                        elif menit == "37": b = a+telu[i]+pitu[i]
                        elif menit == "38": b = a+telu[i]+welu[i]
                        elif menit == "39": b = a+telu[i]+sanga[i]
                        elif menit == "40": b = a+papat[i]+nol[i]
                        elif menit == "41": b = a+papat[i]+siji[i]
                        elif menit == "42": b = a+papat[i]+loro[i]
                        elif menit == "43": b = a+papat[i]+telu[i]
			elif menit == "44": b = a+papat[i]+papat[i]
                        elif menit == "45": b = a+papat[i]+lima[i]
                        elif menit == "46": b = a+papat[i]+enem[i]
                        elif menit == "47": b = a+papat[i]+pitu[i]
                        elif menit == "48": b = a+papat[i]+welu[i]
                        elif menit == "49": b = a+papat[i]+sanga[i]
                        elif menit == "50": b = a+lima[i]+nol[i]
                        elif menit == "51": b = a+lima[i]+siji[i]
                        elif menit == "52": b = a+lima[i]+loro[i]
                        elif menit == "53": b = a+lima[i]+telu[i]
                        elif menit == "54": b = a+lima[i]+papat[i]
                        elif menit == "55": b = a+lima[i]+lima[i]
                        elif menit == "56": b = a+lima[i]+enem[i]
                        elif menit == "57": b = a+lima[i]+pitu[i]
                        elif menit == "58": b = a+lima[i]+welu[i]
                        elif menit == "59": b = a+lima[i]+sanga[i]
		elif jam == "11":
			a = siji[i]+siji[i]+titik[i]
			if menit == "00": b = a+nol[i]+nol[i]
			elif menit == "01": b = a+nol[i]+siji[i]
			elif menit == "02": b = a+nol[i]+loro[i]
			elif menit == "03": b = a+nol[i]+telu[i]
                        elif menit == "04": b = a+nol[i]+papat[i]
			elif menit == "05": b = a+nol[i]+lima[i]
                        elif menit == "06": b = a+nol[i]+enem[i]
			elif menit == "07": b = a+nol[i]+pitu[i]
                        elif menit == "08": b = a+nol[i]+welu[i]
			elif menit == "09": b = a+nol[i]+sanga[i]
                        elif menit == "10": b = a+siji[i]+nol[i]
			elif menit == "11": b = a+siji[i]+siji[i]
                        elif menit == "12": b = a+siji[i]+loro[i]
                        elif menit == "13": b = a+siji[i]+telu[i]
                        elif menit == "14": b = a+siji[i]+papat[i]
                        elif menit == "15": b = a+siji[i]+lima[i]
                        elif menit == "16": b = a+siji[i]+enem[i]
                        elif menit == "17": b = a+siji[i]+pitu[i]
                        elif menit == "18": b = a+siji[i]+welu[i]
                        elif menit == "19": b = a+siji[i]+sanga[i]
			elif menit == "20": b = a+loro[i]+nol[i]
                        elif menit == "21": b = a+loro[i]+siji[i]
                        elif menit == "22": b = a+loro[i]+loro[i]
                        elif menit == "23": b = a+loro[i]+telu[i]
                        elif menit == "24": b = a+loro[i]+papat[i]
                        elif menit == "25": b = a+loro[i]+lima[i]
			elif menit == "26": b = a+loro[i]+enem[i]
                        elif menit == "27": b = a+loro[i]+pitu[i]
                        elif menit == "28": b = a+loro[i]+welu[i]
                        elif menit == "29": b = a+loro[i]+sanga[i]
                        elif menit == "30": b = a+telu[i]+nol[i]
                        elif menit == "31": b = a+telu[i]+siji[i]
                        elif menit == "32": b = a+telu[i]+loro[i]
                        elif menit == "33": b = a+telu[i]+telu[i]
                        elif menit == "34": b = a+telu[i]+papat[i]
                        elif menit == "35": b = a+telu[i]+lima[i]
                        elif menit == "36": b = a+telu[i]+enem[i]
                        elif menit == "37": b = a+telu[i]+pitu[i]
                        elif menit == "38": b = a+telu[i]+welu[i]
                        elif menit == "39": b = a+telu[i]+sanga[i]
                        elif menit == "40": b = a+papat[i]+nol[i]
                        elif menit == "41": b = a+papat[i]+siji[i]
                        elif menit == "42": b = a+papat[i]+loro[i]
                        elif menit == "43": b = a+papat[i]+telu[i]
			elif menit == "44": b = a+papat[i]+papat[i]
                        elif menit == "45": b = a+papat[i]+lima[i]
                        elif menit == "46": b = a+papat[i]+enem[i]
                        elif menit == "47": b = a+papat[i]+pitu[i]
                        elif menit == "48": b = a+papat[i]+welu[i]
                        elif menit == "49": b = a+papat[i]+sanga[i]
                        elif menit == "50": b = a+lima[i]+nol[i]
                        elif menit == "51": b = a+lima[i]+siji[i]
                        elif menit == "52": b = a+lima[i]+loro[i]
                        elif menit == "53": b = a+lima[i]+telu[i]
                        elif menit == "54": b = a+lima[i]+papat[i]
                        elif menit == "55": b = a+lima[i]+lima[i]
                        elif menit == "56": b = a+lima[i]+enem[i]
                        elif menit == "57": b = a+lima[i]+pitu[i]
                        elif menit == "58": b = a+lima[i]+welu[i]
                        elif menit == "59": b = a+lima[i]+sanga[i]
		elif jam == "12":
			a = siji[i]+loro[i]+titik[i]
			if menit == "00": b = a+nol[i]+nol[i]
			elif menit == "01": b = a+nol[i]+siji[i]
			elif menit == "02": b = a+nol[i]+loro[i]
			elif menit == "03": b = a+nol[i]+telu[i]
                        elif menit == "04": b = a+nol[i]+papat[i]
			elif menit == "05": b = a+nol[i]+lima[i]
                        elif menit == "06": b = a+nol[i]+enem[i]
			elif menit == "07": b = a+nol[i]+pitu[i]
                        elif menit == "08": b = a+nol[i]+welu[i]
			elif menit == "09": b = a+nol[i]+sanga[i]
                        elif menit == "10": b = a+siji[i]+nol[i]
			elif menit == "11": b = a+siji[i]+siji[i]
                        elif menit == "12": b = a+siji[i]+loro[i]
                        elif menit == "13": b = a+siji[i]+telu[i]
                        elif menit == "14": b = a+siji[i]+papat[i]
                        elif menit == "15": b = a+siji[i]+lima[i]
                        elif menit == "16": b = a+siji[i]+enem[i]
                        elif menit == "17": b = a+siji[i]+pitu[i]
                        elif menit == "18": b = a+siji[i]+welu[i]
                        elif menit == "19": b = a+siji[i]+sanga[i]
			elif menit == "20": b = a+loro[i]+nol[i]
                        elif menit == "21": b = a+loro[i]+siji[i]
                        elif menit == "22": b = a+loro[i]+loro[i]
                        elif menit == "23": b = a+loro[i]+telu[i]
                        elif menit == "24": b = a+loro[i]+papat[i]
                        elif menit == "25": b = a+loro[i]+lima[i]
			elif menit == "26": b = a+loro[i]+enem[i]
                        elif menit == "27": b = a+loro[i]+pitu[i]
                        elif menit == "28": b = a+loro[i]+welu[i]
                        elif menit == "29": b = a+loro[i]+sanga[i]
                        elif menit == "30": b = a+telu[i]+nol[i]
                        elif menit == "31": b = a+telu[i]+siji[i]
                        elif menit == "32": b = a+telu[i]+loro[i]
                        elif menit == "33": b = a+telu[i]+telu[i]
                        elif menit == "34": b = a+telu[i]+papat[i]
                        elif menit == "35": b = a+telu[i]+lima[i]
                        elif menit == "36": b = a+telu[i]+enem[i]
                        elif menit == "37": b = a+telu[i]+pitu[i]
                        elif menit == "38": b = a+telu[i]+welu[i]
                        elif menit == "39": b = a+telu[i]+sanga[i]
                        elif menit == "40": b = a+papat[i]+nol[i]
                        elif menit == "41": b = a+papat[i]+siji[i]
                        elif menit == "42": b = a+papat[i]+loro[i]
                        elif menit == "43": b = a+papat[i]+telu[i]
			elif menit == "44": b = a+papat[i]+papat[i]
                        elif menit == "45": b = a+papat[i]+lima[i]
                        elif menit == "46": b = a+papat[i]+enem[i]
                        elif menit == "47": b = a+papat[i]+pitu[i]
                        elif menit == "48": b = a+papat[i]+welu[i]
                        elif menit == "49": b = a+papat[i]+sanga[i]
                        elif menit == "50": b = a+lima[i]+nol[i]
                        elif menit == "51": b = a+lima[i]+siji[i]
                        elif menit == "52": b = a+lima[i]+loro[i]
                        elif menit == "53": b = a+lima[i]+telu[i]
                        elif menit == "54": b = a+lima[i]+papat[i]
                        elif menit == "55": b = a+lima[i]+lima[i]
                        elif menit == "56": b = a+lima[i]+enem[i]
                        elif menit == "57": b = a+lima[i]+pitu[i]
                        elif menit == "58": b = a+lima[i]+welu[i]
                        elif menit == "59": b = a+lima[i]+sanga[i]
		elif jam == "13":
			a = siji[i]+telu[i]+titik[i]
			if menit == "00": b = a+nol[i]+nol[i]
			elif menit == "01": b = a+nol[i]+siji[i]
			elif menit == "02": b = a+nol[i]+loro[i]
			elif menit == "03": b = a+nol[i]+telu[i]
                        elif menit == "04": b = a+nol[i]+papat[i]
			elif menit == "05": b = a+nol[i]+lima[i]
                        elif menit == "06": b = a+nol[i]+enem[i]
			elif menit == "07": b = a+nol[i]+pitu[i]
                        elif menit == "08": b = a+nol[i]+welu[i]
			elif menit == "09": b = a+nol[i]+sanga[i]
                        elif menit == "10": b = a+siji[i]+nol[i]
			elif menit == "11": b = a+siji[i]+siji[i]
                        elif menit == "12": b = a+siji[i]+loro[i]
                        elif menit == "13": b = a+siji[i]+telu[i]
                        elif menit == "14": b = a+siji[i]+papat[i]
                        elif menit == "15": b = a+siji[i]+lima[i]
                        elif menit == "16": b = a+siji[i]+enem[i]
                        elif menit == "17": b = a+siji[i]+pitu[i]
                        elif menit == "18": b = a+siji[i]+welu[i]
                        elif menit == "19": b = a+siji[i]+sanga[i]
			elif menit == "20": b = a+loro[i]+nol[i]
                        elif menit == "21": b = a+loro[i]+siji[i]
                        elif menit == "22": b = a+loro[i]+loro[i]
                        elif menit == "23": b = a+loro[i]+telu[i]
                        elif menit == "24": b = a+loro[i]+papat[i]
                        elif menit == "25": b = a+loro[i]+lima[i]
			elif menit == "26": b = a+loro[i]+enem[i]
                        elif menit == "27": b = a+loro[i]+pitu[i]
                        elif menit == "28": b = a+loro[i]+welu[i]
                        elif menit == "29": b = a+loro[i]+sanga[i]
                        elif menit == "30": b = a+telu[i]+nol[i]
                        elif menit == "31": b = a+telu[i]+siji[i]
                        elif menit == "32": b = a+telu[i]+loro[i]
                        elif menit == "33": b = a+telu[i]+telu[i]
                        elif menit == "34": b = a+telu[i]+papat[i]
                        elif menit == "35": b = a+telu[i]+lima[i]
                        elif menit == "36": b = a+telu[i]+enem[i]
                        elif menit == "37": b = a+telu[i]+pitu[i]
                        elif menit == "38": b = a+telu[i]+welu[i]
                        elif menit == "39": b = a+telu[i]+sanga[i]
                        elif menit == "40": b = a+papat[i]+nol[i]
                        elif menit == "41": b = a+papat[i]+siji[i]
                        elif menit == "42": b = a+papat[i]+loro[i]
                        elif menit == "43": b = a+papat[i]+telu[i]
			elif menit == "44": b = a+papat[i]+papat[i]
                        elif menit == "45": b = a+papat[i]+lima[i]
                        elif menit == "46": b = a+papat[i]+enem[i]
                        elif menit == "47": b = a+papat[i]+pitu[i]
                        elif menit == "48": b = a+papat[i]+welu[i]
                        elif menit == "49": b = a+papat[i]+sanga[i]
                        elif menit == "50": b = a+lima[i]+nol[i]
                        elif menit == "51": b = a+lima[i]+siji[i]
                        elif menit == "52": b = a+lima[i]+loro[i]
                        elif menit == "53": b = a+lima[i]+telu[i]
                        elif menit == "54": b = a+lima[i]+papat[i]
                        elif menit == "55": b = a+lima[i]+lima[i]
                        elif menit == "56": b = a+lima[i]+enem[i]
                        elif menit == "57": b = a+lima[i]+pitu[i]
                        elif menit == "58": b = a+lima[i]+welu[i]
                        elif menit == "59": b = a+lima[i]+sanga[i]
		elif jam == "14":
			a = siji[i]+papat[i]+titik[i]
			if menit == "00": b = a+nol[i]+nol[i]
			elif menit == "01": b = a+nol[i]+siji[i]
			elif menit == "02": b = a+nol[i]+loro[i]
			elif menit == "03": b = a+nol[i]+telu[i]
                        elif menit == "04": b = a+nol[i]+papat[i]
			elif menit == "05": b = a+nol[i]+lima[i]
                        elif menit == "06": b = a+nol[i]+enem[i]
			elif menit == "07": b = a+nol[i]+pitu[i]
                        elif menit == "08": b = a+nol[i]+welu[i]
			elif menit == "09": b = a+nol[i]+sanga[i]
                        elif menit == "10": b = a+siji[i]+nol[i]
			elif menit == "11": b = a+siji[i]+siji[i]
                        elif menit == "12": b = a+siji[i]+loro[i]
                        elif menit == "13": b = a+siji[i]+telu[i]
                        elif menit == "14": b = a+siji[i]+papat[i]
                        elif menit == "15": b = a+siji[i]+lima[i]
                        elif menit == "16": b = a+siji[i]+enem[i]
                        elif menit == "17": b = a+siji[i]+pitu[i]
                        elif menit == "18": b = a+siji[i]+welu[i]
                        elif menit == "19": b = a+siji[i]+sanga[i]
			elif menit == "20": b = a+loro[i]+nol[i]
                        elif menit == "21": b = a+loro[i]+siji[i]
                        elif menit == "22": b = a+loro[i]+loro[i]
                        elif menit == "23": b = a+loro[i]+telu[i]
                        elif menit == "24": b = a+loro[i]+papat[i]
                        elif menit == "25": b = a+loro[i]+lima[i]
			elif menit == "26": b = a+loro[i]+enem[i]
                        elif menit == "27": b = a+loro[i]+pitu[i]
                        elif menit == "28": b = a+loro[i]+welu[i]
                        elif menit == "29": b = a+loro[i]+sanga[i]
                        elif menit == "30": b = a+telu[i]+nol[i]
                        elif menit == "31": b = a+telu[i]+siji[i]
                        elif menit == "32": b = a+telu[i]+loro[i]
                        elif menit == "33": b = a+telu[i]+telu[i]
                        elif menit == "34": b = a+telu[i]+papat[i]
                        elif menit == "35": b = a+telu[i]+lima[i]
                        elif menit == "36": b = a+telu[i]+enem[i]
                        elif menit == "37": b = a+telu[i]+pitu[i]
                        elif menit == "38": b = a+telu[i]+welu[i]
                        elif menit == "39": b = a+telu[i]+sanga[i]
                        elif menit == "40": b = a+papat[i]+nol[i]
                        elif menit == "41": b = a+papat[i]+siji[i]
                        elif menit == "42": b = a+papat[i]+loro[i]
                        elif menit == "43": b = a+papat[i]+telu[i]
			elif menit == "44": b = a+papat[i]+papat[i]
                        elif menit == "45": b = a+papat[i]+lima[i]
                        elif menit == "46": b = a+papat[i]+enem[i]
                        elif menit == "47": b = a+papat[i]+pitu[i]
                        elif menit == "48": b = a+papat[i]+welu[i]
                        elif menit == "49": b = a+papat[i]+sanga[i]
                        elif menit == "50": b = a+lima[i]+nol[i]
                        elif menit == "51": b = a+lima[i]+siji[i]
                        elif menit == "52": b = a+lima[i]+loro[i]
                        elif menit == "53": b = a+lima[i]+telu[i]
                        elif menit == "54": b = a+lima[i]+papat[i]
                        elif menit == "55": b = a+lima[i]+lima[i]
                        elif menit == "56": b = a+lima[i]+enem[i]
                        elif menit == "57": b = a+lima[i]+pitu[i]
                        elif menit == "58": b = a+lima[i]+welu[i]
                        elif menit == "59": b = a+lima[i]+sanga[i]
		elif jam == "15":
			a = siji[i]+lima[i]+titik[i]
			if menit == "00": b = a+nol[i]+nol[i]
			elif menit == "01": b = a+nol[i]+siji[i]
			elif menit == "02": b = a+nol[i]+loro[i]
			elif menit == "03": b = a+nol[i]+telu[i]
                        elif menit == "04": b = a+nol[i]+papat[i]
			elif menit == "05": b = a+nol[i]+lima[i]
                        elif menit == "06": b = a+nol[i]+enem[i]
			elif menit == "07": b = a+nol[i]+pitu[i]
                        elif menit == "08": b = a+nol[i]+welu[i]
			elif menit == "09": b = a+nol[i]+sanga[i]
                        elif menit == "10": b = a+siji[i]+nol[i]
			elif menit == "11": b = a+siji[i]+siji[i]
                        elif menit == "12": b = a+siji[i]+loro[i]
                        elif menit == "13": b = a+siji[i]+telu[i]
                        elif menit == "14": b = a+siji[i]+papat[i]
                        elif menit == "15": b = a+siji[i]+lima[i]
                        elif menit == "16": b = a+siji[i]+enem[i]
                        elif menit == "17": b = a+siji[i]+pitu[i]
                        elif menit == "18": b = a+siji[i]+welu[i]
                        elif menit == "19": b = a+siji[i]+sanga[i]
			elif menit == "20": b = a+loro[i]+nol[i]
                        elif menit == "21": b = a+loro[i]+siji[i]
                        elif menit == "22": b = a+loro[i]+loro[i]
                        elif menit == "23": b = a+loro[i]+telu[i]
                        elif menit == "24": b = a+loro[i]+papat[i]
                        elif menit == "25": b = a+loro[i]+lima[i]
			elif menit == "26": b = a+loro[i]+enem[i]
                        elif menit == "27": b = a+loro[i]+pitu[i]
                        elif menit == "28": b = a+loro[i]+welu[i]
                        elif menit == "29": b = a+loro[i]+sanga[i]
                        elif menit == "30": b = a+telu[i]+nol[i]
                        elif menit == "31": b = a+telu[i]+siji[i]
                        elif menit == "32": b = a+telu[i]+loro[i]
                        elif menit == "33": b = a+telu[i]+telu[i]
                        elif menit == "34": b = a+telu[i]+papat[i]
                        elif menit == "35": b = a+telu[i]+lima[i]
                        elif menit == "36": b = a+telu[i]+enem[i]
                        elif menit == "37": b = a+telu[i]+pitu[i]
                        elif menit == "38": b = a+telu[i]+welu[i]
                        elif menit == "39": b = a+telu[i]+sanga[i]
                        elif menit == "40": b = a+papat[i]+nol[i]
                        elif menit == "41": b = a+papat[i]+siji[i]
                        elif menit == "42": b = a+papat[i]+loro[i]
                        elif menit == "43": b = a+papat[i]+telu[i]
			elif menit == "44": b = a+papat[i]+papat[i]
                        elif menit == "45": b = a+papat[i]+lima[i]
                        elif menit == "46": b = a+papat[i]+enem[i]
                        elif menit == "47": b = a+papat[i]+pitu[i]
                        elif menit == "48": b = a+papat[i]+welu[i]
                        elif menit == "49": b = a+papat[i]+sanga[i]
                        elif menit == "50": b = a+lima[i]+nol[i]
                        elif menit == "51": b = a+lima[i]+siji[i]
                        elif menit == "52": b = a+lima[i]+loro[i]
                        elif menit == "53": b = a+lima[i]+telu[i]
                        elif menit == "54": b = a+lima[i]+papat[i]
                        elif menit == "55": b = a+lima[i]+lima[i]
                        elif menit == "56": b = a+lima[i]+enem[i]
                        elif menit == "57": b = a+lima[i]+pitu[i]
                        elif menit == "58": b = a+lima[i]+welu[i]
                        elif menit == "59": b = a+lima[i]+sanga[i]
		elif jam == "16":
			a = siji[i]+enem[i]+titik[i]
			if menit == "00": b = a+nol[i]+nol[i]
			elif menit == "01": b = a+nol[i]+siji[i]
			elif menit == "02": b = a+nol[i]+loro[i]
			elif menit == "03": b = a+nol[i]+telu[i]
                        elif menit == "04": b = a+nol[i]+papat[i]
			elif menit == "05": b = a+nol[i]+lima[i]
                        elif menit == "06": b = a+nol[i]+enem[i]
			elif menit == "07": b = a+nol[i]+pitu[i]
                        elif menit == "08": b = a+nol[i]+welu[i]
			elif menit == "09": b = a+nol[i]+sanga[i]
                        elif menit == "10": b = a+siji[i]+nol[i]
			elif menit == "11": b = a+siji[i]+siji[i]
                        elif menit == "12": b = a+siji[i]+loro[i]
                        elif menit == "13": b = a+siji[i]+telu[i]
                        elif menit == "14": b = a+siji[i]+papat[i]
                        elif menit == "15": b = a+siji[i]+lima[i]
                        elif menit == "16": b = a+siji[i]+enem[i]
                        elif menit == "17": b = a+siji[i]+pitu[i]
                        elif menit == "18": b = a+siji[i]+welu[i]
                        elif menit == "19": b = a+siji[i]+sanga[i]
			elif menit == "20": b = a+loro[i]+nol[i]
                        elif menit == "21": b = a+loro[i]+siji[i]
                        elif menit == "22": b = a+loro[i]+loro[i]
                        elif menit == "23": b = a+loro[i]+telu[i]
                        elif menit == "24": b = a+loro[i]+papat[i]
                        elif menit == "25": b = a+loro[i]+lima[i]
			elif menit == "26": b = a+loro[i]+enem[i]
                        elif menit == "27": b = a+loro[i]+pitu[i]
                        elif menit == "28": b = a+loro[i]+welu[i]
                        elif menit == "29": b = a+loro[i]+sanga[i]
                        elif menit == "30": b = a+telu[i]+nol[i]
                        elif menit == "31": b = a+telu[i]+siji[i]
                        elif menit == "32": b = a+telu[i]+loro[i]
                        elif menit == "33": b = a+telu[i]+telu[i]
                        elif menit == "34": b = a+telu[i]+papat[i]
                        elif menit == "35": b = a+telu[i]+lima[i]
                        elif menit == "36": b = a+telu[i]+enem[i]
                        elif menit == "37": b = a+telu[i]+pitu[i]
                        elif menit == "38": b = a+telu[i]+welu[i]
                        elif menit == "39": b = a+telu[i]+sanga[i]
                        elif menit == "40": b = a+papat[i]+nol[i]
                        elif menit == "41": b = a+papat[i]+siji[i]
                        elif menit == "42": b = a+papat[i]+loro[i]
                        elif menit == "43": b = a+papat[i]+telu[i]
			elif menit == "44": b = a+papat[i]+papat[i]
                        elif menit == "45": b = a+papat[i]+lima[i]
                        elif menit == "46": b = a+papat[i]+enem[i]
                        elif menit == "47": b = a+papat[i]+pitu[i]
                        elif menit == "48": b = a+papat[i]+welu[i]
                        elif menit == "49": b = a+papat[i]+sanga[i]
                        elif menit == "50": b = a+lima[i]+nol[i]
                        elif menit == "51": b = a+lima[i]+siji[i]
                        elif menit == "52": b = a+lima[i]+loro[i]
                        elif menit == "53": b = a+lima[i]+telu[i]
                        elif menit == "54": b = a+lima[i]+papat[i]
                        elif menit == "55": b = a+lima[i]+lima[i]
                        elif menit == "56": b = a+lima[i]+enem[i]
                        elif menit == "57": b = a+lima[i]+pitu[i]
                        elif menit == "58": b = a+lima[i]+welu[i]
                        elif menit == "59": b = a+lima[i]+sanga[i]
		elif jam == "17":
			a = siji[i]+pitu[i]+titik[i]
			if menit == "00": b = a+nol[i]+nol[i]
			elif menit == "01": b = a+nol[i]+siji[i]
			elif menit == "02": b = a+nol[i]+loro[i]
			elif menit == "03": b = a+nol[i]+telu[i]
                        elif menit == "04": b = a+nol[i]+papat[i]
			elif menit == "05": b = a+nol[i]+lima[i]
                        elif menit == "06": b = a+nol[i]+enem[i]
			elif menit == "07": b = a+nol[i]+pitu[i]
                        elif menit == "08": b = a+nol[i]+welu[i]
			elif menit == "09": b = a+nol[i]+sanga[i]
                        elif menit == "10": b = a+siji[i]+nol[i]
			elif menit == "11": b = a+siji[i]+siji[i]
                        elif menit == "12": b = a+siji[i]+loro[i]
                        elif menit == "13": b = a+siji[i]+telu[i]
                        elif menit == "14": b = a+siji[i]+papat[i]
                        elif menit == "15": b = a+siji[i]+lima[i]
                        elif menit == "16": b = a+siji[i]+enem[i]
                        elif menit == "17": b = a+siji[i]+pitu[i]
                        elif menit == "18": b = a+siji[i]+welu[i]
                        elif menit == "19": b = a+siji[i]+sanga[i]
			elif menit == "20": b = a+loro[i]+nol[i]
                        elif menit == "21": b = a+loro[i]+siji[i]
                        elif menit == "22": b = a+loro[i]+loro[i]
                        elif menit == "23": b = a+loro[i]+telu[i]
                        elif menit == "24": b = a+loro[i]+papat[i]
                        elif menit == "25": b = a+loro[i]+lima[i]
			elif menit == "26": b = a+loro[i]+enem[i]
                        elif menit == "27": b = a+loro[i]+pitu[i]
                        elif menit == "28": b = a+loro[i]+welu[i]
                        elif menit == "29": b = a+loro[i]+sanga[i]
                        elif menit == "30": b = a+telu[i]+nol[i]
                        elif menit == "31": b = a+telu[i]+siji[i]
                        elif menit == "32": b = a+telu[i]+loro[i]
                        elif menit == "33": b = a+telu[i]+telu[i]
                        elif menit == "34": b = a+telu[i]+papat[i]
                        elif menit == "35": b = a+telu[i]+lima[i]
                        elif menit == "36": b = a+telu[i]+enem[i]
                        elif menit == "37": b = a+telu[i]+pitu[i]
                        elif menit == "38": b = a+telu[i]+welu[i]
                        elif menit == "39": b = a+telu[i]+sanga[i]
                        elif menit == "40": b = a+papat[i]+nol[i]
                        elif menit == "41": b = a+papat[i]+siji[i]
                        elif menit == "42": b = a+papat[i]+loro[i]
                        elif menit == "43": b = a+papat[i]+telu[i]
			elif menit == "44": b = a+papat[i]+papat[i]
                        elif menit == "45": b = a+papat[i]+lima[i]
                        elif menit == "46": b = a+papat[i]+enem[i]
                        elif menit == "47": b = a+papat[i]+pitu[i]
                        elif menit == "48": b = a+papat[i]+welu[i]
                        elif menit == "49": b = a+papat[i]+sanga[i]
                        elif menit == "50": b = a+lima[i]+nol[i]
                        elif menit == "51": b = a+lima[i]+siji[i]
                        elif menit == "52": b = a+lima[i]+loro[i]
                        elif menit == "53": b = a+lima[i]+telu[i]
                        elif menit == "54": b = a+lima[i]+papat[i]
                        elif menit == "55": b = a+lima[i]+lima[i]
                        elif menit == "56": b = a+lima[i]+enem[i]
                        elif menit == "57": b = a+lima[i]+pitu[i]
                        elif menit == "58": b = a+lima[i]+welu[i]
                        elif menit == "59": b = a+lima[i]+sanga[i]
		elif jam == "18":
			a = siji[i]+welu[i]+titik[i]
			if menit == "00": b = a+nol[i]+nol[i]
			elif menit == "01": b = a+nol[i]+siji[i]
			elif menit == "02": b = a+nol[i]+loro[i]
			elif menit == "03": b = a+nol[i]+telu[i]
                        elif menit == "04": b = a+nol[i]+papat[i]
			elif menit == "05": b = a+nol[i]+lima[i]
                        elif menit == "06": b = a+nol[i]+enem[i]
			elif menit == "07": b = a+nol[i]+pitu[i]
                        elif menit == "08": b = a+nol[i]+welu[i]
			elif menit == "09": b = a+nol[i]+sanga[i]
                        elif menit == "10": b = a+siji[i]+nol[i]
			elif menit == "11": b = a+siji[i]+siji[i]
                        elif menit == "12": b = a+siji[i]+loro[i]
                        elif menit == "13": b = a+siji[i]+telu[i]
                        elif menit == "14": b = a+siji[i]+papat[i]
                        elif menit == "15": b = a+siji[i]+lima[i]
                        elif menit == "16": b = a+siji[i]+enem[i]
                        elif menit == "17": b = a+siji[i]+pitu[i]
                        elif menit == "18": b = a+siji[i]+welu[i]
                        elif menit == "19": b = a+siji[i]+sanga[i]
			elif menit == "20": b = a+loro[i]+nol[i]
                        elif menit == "21": b = a+loro[i]+siji[i]
                        elif menit == "22": b = a+loro[i]+loro[i]
                        elif menit == "23": b = a+loro[i]+telu[i]
                        elif menit == "24": b = a+loro[i]+papat[i]
                        elif menit == "25": b = a+loro[i]+lima[i]
			elif menit == "26": b = a+loro[i]+enem[i]
                        elif menit == "27": b = a+loro[i]+pitu[i]
                        elif menit == "28": b = a+loro[i]+welu[i]
                        elif menit == "29": b = a+loro[i]+sanga[i]
                        elif menit == "30": b = a+telu[i]+nol[i]
                        elif menit == "31": b = a+telu[i]+siji[i]
                        elif menit == "32": b = a+telu[i]+loro[i]
                        elif menit == "33": b = a+telu[i]+telu[i]
                        elif menit == "34": b = a+telu[i]+papat[i]
                        elif menit == "35": b = a+telu[i]+lima[i]
                        elif menit == "36": b = a+telu[i]+enem[i]
                        elif menit == "37": b = a+telu[i]+pitu[i]
                        elif menit == "38": b = a+telu[i]+welu[i]
                        elif menit == "39": b = a+telu[i]+sanga[i]
                        elif menit == "40": b = a+papat[i]+nol[i]
                        elif menit == "41": b = a+papat[i]+siji[i]
                        elif menit == "42": b = a+papat[i]+loro[i]
                        elif menit == "43": b = a+papat[i]+telu[i]
			elif menit == "44": b = a+papat[i]+papat[i]
                        elif menit == "45": b = a+papat[i]+lima[i]
                        elif menit == "46": b = a+papat[i]+enem[i]
                        elif menit == "47": b = a+papat[i]+pitu[i]
                        elif menit == "48": b = a+papat[i]+welu[i]
                        elif menit == "49": b = a+papat[i]+sanga[i]
                        elif menit == "50": b = a+lima[i]+nol[i]
                        elif menit == "51": b = a+lima[i]+siji[i]
                        elif menit == "52": b = a+lima[i]+loro[i]
                        elif menit == "53": b = a+lima[i]+telu[i]
                        elif menit == "54": b = a+lima[i]+papat[i]
                        elif menit == "55": b = a+lima[i]+lima[i]
                        elif menit == "56": b = a+lima[i]+enem[i]
                        elif menit == "57": b = a+lima[i]+pitu[i]
                        elif menit == "58": b = a+lima[i]+welu[i]
                        elif menit == "59": b = a+lima[i]+sanga[i]
		elif jam == "19":
			a = siji[i]+sanga[i]+titik[i]
			if menit == "00": b = a+nol[i]+nol[i]
			elif menit == "01": b = a+nol[i]+siji[i]
			elif menit == "02": b = a+nol[i]+loro[i]
			elif menit == "03": b = a+nol[i]+telu[i]
                        elif menit == "04": b = a+nol[i]+papat[i]
			elif menit == "05": b = a+nol[i]+lima[i]
                        elif menit == "06": b = a+nol[i]+enem[i]
			elif menit == "07": b = a+nol[i]+pitu[i]
                        elif menit == "08": b = a+nol[i]+welu[i]
			elif menit == "09": b = a+nol[i]+sanga[i]
                        elif menit == "10": b = a+siji[i]+nol[i]
			elif menit == "11": b = a+siji[i]+siji[i]
                        elif menit == "12": b = a+siji[i]+loro[i]
                        elif menit == "13": b = a+siji[i]+telu[i]
                        elif menit == "14": b = a+siji[i]+papat[i]
                        elif menit == "15": b = a+siji[i]+lima[i]
                        elif menit == "16": b = a+siji[i]+enem[i]
                        elif menit == "17": b = a+siji[i]+pitu[i]
                        elif menit == "18": b = a+siji[i]+welu[i]
                        elif menit == "19": b = a+siji[i]+sanga[i]
			elif menit == "20": b = a+loro[i]+nol[i]
                        elif menit == "21": b = a+loro[i]+siji[i]
                        elif menit == "22": b = a+loro[i]+loro[i]
                        elif menit == "23": b = a+loro[i]+telu[i]
                        elif menit == "24": b = a+loro[i]+papat[i]
                        elif menit == "25": b = a+loro[i]+lima[i]
			elif menit == "26": b = a+loro[i]+enem[i]
                        elif menit == "27": b = a+loro[i]+pitu[i]
                        elif menit == "28": b = a+loro[i]+welu[i]
                        elif menit == "29": b = a+loro[i]+sanga[i]
                        elif menit == "30": b = a+telu[i]+nol[i]
                        elif menit == "31": b = a+telu[i]+siji[i]
                        elif menit == "32": b = a+telu[i]+loro[i]
                        elif menit == "33": b = a+telu[i]+telu[i]
                        elif menit == "34": b = a+telu[i]+papat[i]
                        elif menit == "35": b = a+telu[i]+lima[i]
                        elif menit == "36": b = a+telu[i]+enem[i]
                        elif menit == "37": b = a+telu[i]+pitu[i]
                        elif menit == "38": b = a+telu[i]+welu[i]
                        elif menit == "39": b = a+telu[i]+sanga[i]
                        elif menit == "40": b = a+papat[i]+nol[i]
                        elif menit == "41": b = a+papat[i]+siji[i]
                        elif menit == "42": b = a+papat[i]+loro[i]
                        elif menit == "43": b = a+papat[i]+telu[i]
			elif menit == "44": b = a+papat[i]+papat[i]
                        elif menit == "45": b = a+papat[i]+lima[i]
                        elif menit == "46": b = a+papat[i]+enem[i]
                        elif menit == "47": b = a+papat[i]+pitu[i]
                        elif menit == "48": b = a+papat[i]+welu[i]
                        elif menit == "49": b = a+papat[i]+sanga[i]
                        elif menit == "50": b = a+lima[i]+nol[i]
                        elif menit == "51": b = a+lima[i]+siji[i]
                        elif menit == "52": b = a+lima[i]+loro[i]
                        elif menit == "53": b = a+lima[i]+telu[i]
                        elif menit == "54": b = a+lima[i]+papat[i]
                        elif menit == "55": b = a+lima[i]+lima[i]
                        elif menit == "56": b = a+lima[i]+enem[i]
                        elif menit == "57": b = a+lima[i]+pitu[i]
                        elif menit == "58": b = a+lima[i]+welu[i]
                        elif menit == "59": b = a+lima[i]+sanga[i]
		elif jam == "20":
			a = loro[i]+nol[i]+titik[i]
			if menit == "00": b = a+nol[i]+nol[i]
			elif menit == "01": b = a+nol[i]+siji[i]
			elif menit == "02": b = a+nol[i]+loro[i]
			elif menit == "03": b = a+nol[i]+telu[i]
                        elif menit == "04": b = a+nol[i]+papat[i]
			elif menit == "05": b = a+nol[i]+lima[i]
                        elif menit == "06": b = a+nol[i]+enem[i]
			elif menit == "07": b = a+nol[i]+pitu[i]
                        elif menit == "08": b = a+nol[i]+welu[i]
			elif menit == "09": b = a+nol[i]+sanga[i]
                        elif menit == "10": b = a+siji[i]+nol[i]
			elif menit == "11": b = a+siji[i]+siji[i]
                        elif menit == "12": b = a+siji[i]+loro[i]
                        elif menit == "13": b = a+siji[i]+telu[i]
                        elif menit == "14": b = a+siji[i]+papat[i]
                        elif menit == "15": b = a+siji[i]+lima[i]
                        elif menit == "16": b = a+siji[i]+enem[i]
                        elif menit == "17": b = a+siji[i]+pitu[i]
                        elif menit == "18": b = a+siji[i]+welu[i]
                        elif menit == "19": b = a+siji[i]+sanga[i]
			elif menit == "20": b = a+loro[i]+nol[i]
                        elif menit == "21": b = a+loro[i]+siji[i]
                        elif menit == "22": b = a+loro[i]+loro[i]
                        elif menit == "23": b = a+loro[i]+telu[i]
                        elif menit == "24": b = a+loro[i]+papat[i]
                        elif menit == "25": b = a+loro[i]+lima[i]
			elif menit == "26": b = a+loro[i]+enem[i]
                        elif menit == "27": b = a+loro[i]+pitu[i]
                        elif menit == "28": b = a+loro[i]+welu[i]
                        elif menit == "29": b = a+loro[i]+sanga[i]
                        elif menit == "30": b = a+telu[i]+nol[i]
                        elif menit == "31": b = a+telu[i]+siji[i]
                        elif menit == "32": b = a+telu[i]+loro[i]
                        elif menit == "33": b = a+telu[i]+telu[i]
                        elif menit == "34": b = a+telu[i]+papat[i]
                        elif menit == "35": b = a+telu[i]+lima[i]
                        elif menit == "36": b = a+telu[i]+enem[i]
                        elif menit == "37": b = a+telu[i]+pitu[i]
                        elif menit == "38": b = a+telu[i]+welu[i]
                        elif menit == "39": b = a+telu[i]+sanga[i]
                        elif menit == "40": b = a+papat[i]+nol[i]
                        elif menit == "41": b = a+papat[i]+siji[i]
                        elif menit == "42": b = a+papat[i]+loro[i]
                        elif menit == "43": b = a+papat[i]+telu[i]
			elif menit == "44": b = a+papat[i]+papat[i]
                        elif menit == "45": b = a+papat[i]+lima[i]
                        elif menit == "46": b = a+papat[i]+enem[i]
                        elif menit == "47": b = a+papat[i]+pitu[i]
                        elif menit == "48": b = a+papat[i]+welu[i]
                        elif menit == "49": b = a+papat[i]+sanga[i]
                        elif menit == "50": b = a+lima[i]+nol[i]
                        elif menit == "51": b = a+lima[i]+siji[i]
                        elif menit == "52": b = a+lima[i]+loro[i]
                        elif menit == "53": b = a+lima[i]+telu[i]
                        elif menit == "54": b = a+lima[i]+papat[i]
                        elif menit == "55": b = a+lima[i]+lima[i]
                        elif menit == "56": b = a+lima[i]+enem[i]
                        elif menit == "57": b = a+lima[i]+pitu[i]
                        elif menit == "58": b = a+lima[i]+welu[i]
                        elif menit == "59": b = a+lima[i]+sanga[i]
		elif jam == "21":
			a = loro[i]+siji[i]+titik[i]
			if menit == "00": b = a+nol[i]+nol[i]
			elif menit == "01": b = a+nol[i]+siji[i]
			elif menit == "02": b = a+nol[i]+loro[i]
			elif menit == "03": b = a+nol[i]+telu[i]
                        elif menit == "04": b = a+nol[i]+papat[i]
			elif menit == "05": b = a+nol[i]+lima[i]
                        elif menit == "06": b = a+nol[i]+enem[i]
			elif menit == "07": b = a+nol[i]+pitu[i]
                        elif menit == "08": b = a+nol[i]+welu[i]
			elif menit == "09": b = a+nol[i]+sanga[i]
                        elif menit == "10": b = a+siji[i]+nol[i]
			elif menit == "11": b = a+siji[i]+siji[i]
                        elif menit == "12": b = a+siji[i]+loro[i]
                        elif menit == "13": b = a+siji[i]+telu[i]
                        elif menit == "14": b = a+siji[i]+papat[i]
                        elif menit == "15": b = a+siji[i]+lima[i]
                        elif menit == "16": b = a+siji[i]+enem[i]
                        elif menit == "17": b = a+siji[i]+pitu[i]
                        elif menit == "18": b = a+siji[i]+welu[i]
                        elif menit == "19": b = a+siji[i]+sanga[i]
			elif menit == "20": b = a+loro[i]+nol[i]
                        elif menit == "21": b = a+loro[i]+siji[i]
                        elif menit == "22": b = a+loro[i]+loro[i]
                        elif menit == "23": b = a+loro[i]+telu[i]
                        elif menit == "24": b = a+loro[i]+papat[i]
                        elif menit == "25": b = a+loro[i]+lima[i]
			elif menit == "26": b = a+loro[i]+enem[i]
                        elif menit == "27": b = a+loro[i]+pitu[i]
                        elif menit == "28": b = a+loro[i]+welu[i]
                        elif menit == "29": b = a+loro[i]+sanga[i]
                        elif menit == "30": b = a+telu[i]+nol[i]
                        elif menit == "31": b = a+telu[i]+siji[i]
                        elif menit == "32": b = a+telu[i]+loro[i]
                        elif menit == "33": b = a+telu[i]+telu[i]
                        elif menit == "34": b = a+telu[i]+papat[i]
                        elif menit == "35": b = a+telu[i]+lima[i]
                        elif menit == "36": b = a+telu[i]+enem[i]
                        elif menit == "37": b = a+telu[i]+pitu[i]
                        elif menit == "38": b = a+telu[i]+welu[i]
                        elif menit == "39": b = a+telu[i]+sanga[i]
                        elif menit == "40": b = a+papat[i]+nol[i]
                        elif menit == "41": b = a+papat[i]+siji[i]
                        elif menit == "42": b = a+papat[i]+loro[i]
                        elif menit == "43": b = a+papat[i]+telu[i]
			elif menit == "44": b = a+papat[i]+papat[i]
                        elif menit == "45": b = a+papat[i]+lima[i]
                        elif menit == "46": b = a+papat[i]+enem[i]
                        elif menit == "47": b = a+papat[i]+pitu[i]
                        elif menit == "48": b = a+papat[i]+welu[i]
                        elif menit == "49": b = a+papat[i]+sanga[i]
                        elif menit == "50": b = a+lima[i]+nol[i]
                        elif menit == "51": b = a+lima[i]+siji[i]
                        elif menit == "52": b = a+lima[i]+loro[i]
                        elif menit == "53": b = a+lima[i]+telu[i]
                        elif menit == "54": b = a+lima[i]+papat[i]
                        elif menit == "55": b = a+lima[i]+lima[i]
                        elif menit == "56": b = a+lima[i]+enem[i]
                        elif menit == "57": b = a+lima[i]+pitu[i]
                        elif menit == "58": b = a+lima[i]+welu[i]
                        elif menit == "59": b = a+lima[i]+sanga[i]
		elif jam == "22":
			a = loro[i]+loro[i]+titik[i]
			if menit == "00": b = a+nol[i]+nol[i]
			elif menit == "01": b = a+nol[i]+siji[i]
			elif menit == "02": b = a+nol[i]+loro[i]
			elif menit == "03": b = a+nol[i]+telu[i]
                        elif menit == "04": b = a+nol[i]+papat[i]
			elif menit == "05": b = a+nol[i]+lima[i]
                        elif menit == "06": b = a+nol[i]+enem[i]
			elif menit == "07": b = a+nol[i]+pitu[i]
                        elif menit == "08": b = a+nol[i]+welu[i]
			elif menit == "09": b = a+nol[i]+sanga[i]
                        elif menit == "10": b = a+siji[i]+nol[i]
			elif menit == "11": b = a+siji[i]+siji[i]
                        elif menit == "12": b = a+siji[i]+loro[i]
                        elif menit == "13": b = a+siji[i]+telu[i]
                        elif menit == "14": b = a+siji[i]+papat[i]
                        elif menit == "15": b = a+siji[i]+lima[i]
                        elif menit == "16": b = a+siji[i]+enem[i]
                        elif menit == "17": b = a+siji[i]+pitu[i]
                        elif menit == "18": b = a+siji[i]+welu[i]
                        elif menit == "19": b = a+siji[i]+sanga[i]
			elif menit == "20": b = a+loro[i]+nol[i]
                        elif menit == "21": b = a+loro[i]+siji[i]
                        elif menit == "22": b = a+loro[i]+loro[i]
                        elif menit == "23": b = a+loro[i]+telu[i]
                        elif menit == "24": b = a+loro[i]+papat[i]
                        elif menit == "25": b = a+loro[i]+lima[i]
			elif menit == "26": b = a+loro[i]+enem[i]
                        elif menit == "27": b = a+loro[i]+pitu[i]
                        elif menit == "28": b = a+loro[i]+welu[i]
                        elif menit == "29": b = a+loro[i]+sanga[i]
                        elif menit == "30": b = a+telu[i]+nol[i]
                        elif menit == "31": b = a+telu[i]+siji[i]
                        elif menit == "32": b = a+telu[i]+loro[i]
                        elif menit == "33": b = a+telu[i]+telu[i]
                        elif menit == "34": b = a+telu[i]+papat[i]
                        elif menit == "35": b = a+telu[i]+lima[i]
                        elif menit == "36": b = a+telu[i]+enem[i]
                        elif menit == "37": b = a+telu[i]+pitu[i]
                        elif menit == "38": b = a+telu[i]+welu[i]
                        elif menit == "39": b = a+telu[i]+sanga[i]
                        elif menit == "40": b = a+papat[i]+nol[i]
                        elif menit == "41": b = a+papat[i]+siji[i]
                        elif menit == "42": b = a+papat[i]+loro[i]
                        elif menit == "43": b = a+papat[i]+telu[i]
			elif menit == "44": b = a+papat[i]+papat[i]
                        elif menit == "45": b = a+papat[i]+lima[i]
                        elif menit == "46": b = a+papat[i]+enem[i]
                        elif menit == "47": b = a+papat[i]+pitu[i]
                        elif menit == "48": b = a+papat[i]+welu[i]
                        elif menit == "49": b = a+papat[i]+sanga[i]
                        elif menit == "50": b = a+lima[i]+nol[i]
                        elif menit == "51": b = a+lima[i]+siji[i]
                        elif menit == "52": b = a+lima[i]+loro[i]
                        elif menit == "53": b = a+lima[i]+telu[i]
                        elif menit == "54": b = a+lima[i]+papat[i]
                        elif menit == "55": b = a+lima[i]+lima[i]
                        elif menit == "56": b = a+lima[i]+enem[i]
                        elif menit == "57": b = a+lima[i]+pitu[i]
                        elif menit == "58": b = a+lima[i]+welu[i]
                        elif menit == "59": b = a+lima[i]+sanga[i]
		elif jam == "23":
			a = loro[i]+telu[i]+titik[i]
			if menit == "00": b = a+nol[i]+nol[i]
			elif menit == "01": b = a+nol[i]+siji[i]
			elif menit == "02": b = a+nol[i]+loro[i]
			elif menit == "03": b = a+nol[i]+telu[i]
                        elif menit == "04": b = a+nol[i]+papat[i]
			elif menit == "05": b = a+nol[i]+lima[i]
                        elif menit == "06": b = a+nol[i]+enem[i]
			elif menit == "07": b = a+nol[i]+pitu[i]
                        elif menit == "08": b = a+nol[i]+welu[i]
			elif menit == "09": b = a+nol[i]+sanga[i]
                        elif menit == "10": b = a+siji[i]+nol[i]
			elif menit == "11": b = a+siji[i]+siji[i]
                        elif menit == "12": b = a+siji[i]+loro[i]
                        elif menit == "13": b = a+siji[i]+telu[i]
                        elif menit == "14": b = a+siji[i]+papat[i]
                        elif menit == "15": b = a+siji[i]+lima[i]
                        elif menit == "16": b = a+siji[i]+enem[i]
                        elif menit == "17": b = a+siji[i]+pitu[i]
                        elif menit == "18": b = a+siji[i]+welu[i]
                        elif menit == "19": b = a+siji[i]+sanga[i]
			elif menit == "20": b = a+loro[i]+nol[i]
                        elif menit == "21": b = a+loro[i]+siji[i]
                        elif menit == "22": b = a+loro[i]+loro[i]
                        elif menit == "23": b = a+loro[i]+telu[i]
                        elif menit == "24": b = a+loro[i]+papat[i]
                        elif menit == "25": b = a+loro[i]+lima[i]
			elif menit == "26": b = a+loro[i]+enem[i]
                        elif menit == "27": b = a+loro[i]+pitu[i]
                        elif menit == "28": b = a+loro[i]+welu[i]
                        elif menit == "29": b = a+loro[i]+sanga[i]
                        elif menit == "30": b = a+telu[i]+nol[i]
                        elif menit == "31": b = a+telu[i]+siji[i]
                        elif menit == "32": b = a+telu[i]+loro[i]
                        elif menit == "33": b = a+telu[i]+telu[i]
                        elif menit == "34": b = a+telu[i]+papat[i]
                        elif menit == "35": b = a+telu[i]+lima[i]
                        elif menit == "36": b = a+telu[i]+enem[i]
                        elif menit == "37": b = a+telu[i]+pitu[i]
                        elif menit == "38": b = a+telu[i]+welu[i]
                        elif menit == "39": b = a+telu[i]+sanga[i]
                        elif menit == "40": b = a+papat[i]+nol[i]
                        elif menit == "41": b = a+papat[i]+siji[i]
                        elif menit == "42": b = a+papat[i]+loro[i]
                        elif menit == "43": b = a+papat[i]+telu[i]
			elif menit == "44": b = a+papat[i]+papat[i]
                        elif menit == "45": b = a+papat[i]+lima[i]
                        elif menit == "46": b = a+papat[i]+enem[i]
                        elif menit == "47": b = a+papat[i]+pitu[i]
                        elif menit == "48": b = a+papat[i]+welu[i]
                        elif menit == "49": b = a+papat[i]+sanga[i]
                        elif menit == "50": b = a+lima[i]+nol[i]
                        elif menit == "51": b = a+lima[i]+siji[i]
                        elif menit == "52": b = a+lima[i]+loro[i]
                        elif menit == "53": b = a+lima[i]+telu[i]
                        elif menit == "54": b = a+lima[i]+papat[i]
                        elif menit == "55": b = a+lima[i]+lima[i]
                        elif menit == "56": b = a+lima[i]+enem[i]
                        elif menit == "57": b = a+lima[i]+pitu[i]
                        elif menit == "58": b = a+lima[i]+welu[i]
                        elif menit == "59": b = a+lima[i]+sanga[i]
		elif jam == "24":
			a = loro[i]+papat[i]+titik[i]
			if menit == "00": b = a+nol[i]+nol[i]
			elif menit == "01": b = a+nol[i]+siji[i]
			elif menit == "02": b = a+nol[i]+loro[i]
			elif menit == "03": b = a+nol[i]+telu[i]
                        elif menit == "04": b = a+nol[i]+papat[i]
			elif menit == "05": b = a+nol[i]+lima[i]
                        elif menit == "06": b = a+nol[i]+enem[i]
			elif menit == "07": b = a+nol[i]+pitu[i]
                        elif menit == "08": b = a+nol[i]+welu[i]
			elif menit == "09": b = a+nol[i]+sanga[i]
                        elif menit == "10": b = a+siji[i]+nol[i]
			elif menit == "11": b = a+siji[i]+siji[i]
                        elif menit == "12": b = a+siji[i]+loro[i]
                        elif menit == "13": b = a+siji[i]+telu[i]
                        elif menit == "14": b = a+siji[i]+papat[i]
                        elif menit == "15": b = a+siji[i]+lima[i]
                        elif menit == "16": b = a+siji[i]+enem[i]
                        elif menit == "17": b = a+siji[i]+pitu[i]
                        elif menit == "18": b = a+siji[i]+welu[i]
                        elif menit == "19": b = a+siji[i]+sanga[i]
			elif menit == "20": b = a+loro[i]+nol[i]
                        elif menit == "21": b = a+loro[i]+siji[i]
                        elif menit == "22": b = a+loro[i]+loro[i]
                        elif menit == "23": b = a+loro[i]+telu[i]
                        elif menit == "24": b = a+loro[i]+papat[i]
                        elif menit == "25": b = a+loro[i]+lima[i]
			elif menit == "26": b = a+loro[i]+enem[i]
                        elif menit == "27": b = a+loro[i]+pitu[i]
                        elif menit == "28": b = a+loro[i]+welu[i]
                        elif menit == "29": b = a+loro[i]+sanga[i]
                        elif menit == "30": b = a+telu[i]+nol[i]
                        elif menit == "31": b = a+telu[i]+siji[i]
                        elif menit == "32": b = a+telu[i]+loro[i]
                        elif menit == "33": b = a+telu[i]+telu[i]
                        elif menit == "34": b = a+telu[i]+papat[i]
                        elif menit == "35": b = a+telu[i]+lima[i]
                        elif menit == "36": b = a+telu[i]+enem[i]
                        elif menit == "37": b = a+telu[i]+pitu[i]
                        elif menit == "38": b = a+telu[i]+welu[i]
                        elif menit == "39": b = a+telu[i]+sanga[i]
                        elif menit == "40": b = a+papat[i]+nol[i]
                        elif menit == "41": b = a+papat[i]+siji[i]
                        elif menit == "42": b = a+papat[i]+loro[i]
                        elif menit == "43": b = a+papat[i]+telu[i]
			elif menit == "44": b = a+papat[i]+papat[i]
                        elif menit == "45": b = a+papat[i]+lima[i]
                        elif menit == "46": b = a+papat[i]+enem[i]
                        elif menit == "47": b = a+papat[i]+pitu[i]
                        elif menit == "48": b = a+papat[i]+welu[i]
                        elif menit == "49": b = a+papat[i]+sanga[i]
                        elif menit == "50": b = a+lima[i]+nol[i]
                        elif menit == "51": b = a+lima[i]+siji[i]
                        elif menit == "52": b = a+lima[i]+loro[i]
                        elif menit == "53": b = a+lima[i]+telu[i]
                        elif menit == "54": b = a+lima[i]+papat[i]
                        elif menit == "55": b = a+lima[i]+lima[i]
                        elif menit == "56": b = a+lima[i]+enem[i]
                        elif menit == "57": b = a+lima[i]+pitu[i]
                        elif menit == "58": b = a+lima[i]+welu[i]
                        elif menit == "59": b = a+lima[i]+sanga[i]
		print b

while True:
	out()
	time.sleep(1)
	out()
	time.sleep(1)
